name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Build Rust solver
      run: cargo build --release --manifest-path solver/Cargo.toml
      if: ${{ matrix.php-version != '7.2' && matrix.php-version != '7.3' }}

    - name: Composer install
      run: composer update

    - name: Run phpunit
      run: vendor/bin/phpunit

    - name: Install php-cs-fixer
      run: composer require --dev friendsofphp/php-cs-fixer:^3.0
      if: ${{ matrix.php-version == '8.4' }}

    - name: Run php-cs-fixer
      run: vendor/bin/php-cs-fixer check --verbose --diff
      if: ${{ matrix.php-version == '8.4' }}

    - name: Install phpstan
      run: composer require --dev phpstan/phpstan:^2.0
      if: ${{ matrix.php-version == '8.4' }}

    - name: Run phpstan
      run: vendor/bin/phpstan analyse
      if: ${{ matrix.php-version == '8.4' }}
